apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nodeatomic
    deploymentconfig: nodeatomic
  name: nodeatomic-<new-name>
spec:
  containers:
  - image: image-registry.openshift-image-registry.svc:5000/pvtest/nodeatomic@sha256:ce3fec9d24fc4cb8992e2d2631714a65ac16c6b450e94ec27985128245e0ad9f
    imagePullPolicy: Always
    name: nodeatomic
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 1536Mi
      requests:
        cpu: 50m
        memory: 256Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000660000
    volumeMounts:
    - mountPath: /labs/storage
      name: nodeatomicclaim
  nodeName: ip-10-0-145-39.eu-west-1.compute.internal
  volumes:
  - name: nodeatomicclaim
    persistentVolumeClaim:
      claimName: nodeatomicclaim
